# Schema for the configuration files of the BGM Monitoring module.
bgm_monitoring.settings:
  type: config_object
  label: 'BGM Monitoring settings'
  mapping:
    example:
      type: string
      label: 'Example'
